name: setup-gradle-composite
description: An action to set up a Gradle environment with the checked-out repository, Java, and Gradle setup.

runs:
    using: composite
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
      - uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808