name: Publish

on:
  push:
    branches:
      - 'master'
    paths:
      - 'gradle.properties'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
        release_id: ${{ steps.release.outputs.releaseID }}
    steps:
      - uses: Kas-tle/NetworkCompatible/.github/setup-gradle-composite@master
      - name: Publish
        run: ./gradlew publishAggregatedPublicationToCentralPortal
        env:
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
      - name: Get Version
        id: version
        run: echo "version=$(cat gradle.properties | grep version= | cut -d'=' -f2)" >> $GITHUB_OUTPUT
      - name: Make Release Publication
        if: ${{ success() && github.repository == 'Kas-tle/NetworkCompatible' && github.ref_name == 'master' }}
        id: release
        uses: Kas-tle/base-release-action@65d06f835be34757c6d73c16959c97e92c2a3c7f
        with:
          files: |
            transport-raknet/build/libs/*.jar
          appID: ${{ secrets.RELEASE_APP_ID }}
          appPrivateKey: ${{ secrets.RELEASE_APP_PK }}
          discordWebhook: ${{ secrets.DISCORD_WEBHOOK }}
          tagBase: ${{ steps.version.outputs.version }}
          tagIncrement: false
          tagSeparator: ''
          tagPrefix: ''
          releaseName: ${{ steps.version.outputs.version }}
          releaseBodyDependencyUsage: 'java'
          releaseBodyDependencyJavaGroupId: 'dev.kastle.netty'
          releaseBodyDependencyJavaArtifactId: 'netty-transport-raknet'

  upload-logs:
    name: Upload Logs
    runs-on: ubuntu-latest
    needs: publish

    steps:
    - uses: Kas-tle/release-build-log-action@1b57448eaf9476e6e05450e4ea240449eac2c0d2
      if: ${{ success() && github.repository == 'Kas-tle/NetworkCompatible' && github.ref_name == 'master' }}
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        releaseID: ${{ needs.publish.outputs.release_id }}
