name: Publish

on:
  push:
    branches:
      - 'master'
    paths:
      - 'gradle.properties'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/composite/gradle.yml@master
      - name: Publish
        run: ./gradlew publishAggregatedPublicationToCentralPortal
        env:
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
      - name: Get Version
        id: version
        run: echo "version=$(cat gradle.properties | grep version= | cut -d'=' -f2)" >> $GITHUB_OUTPUT
      - name: Make release
        id: release
        uses: Kas-tle/base-release-action@e2c32c8ad0c00ec21b8a26038689d71776ccb8e9
        with:
          files: |
            transport-raknet/build/libs/*.jar
          appID: ${{ secrets.RELEASE_APP_ID }}
          appPrivateKey: ${{ secrets.RELEASE_APP_PK }}
          discordWebhook: ${{ secrets.DISCORD_WEBHOOK }}
          tagBase: ${{ steps.version.outputs.version }}
          tagIncrement: false
          tagSeparator: ''
          tagPrefix: ''
          releaseName: ${{ steps.version.outputs.version }}